services:
  - mysql
  - postgres
  - redis-server
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3
install:
  - pip install -e ".[dev]"
before_script:
  - "sudo touch /etc/mysql/conf.d/replication.cnf"
  - "sudo chmod 777 /etc/mysql/conf.d/replication.cnf"
  - "echo '[mysqld]' > /etc/mysql/conf.d/replication.cnf"
  - "echo 'log-bin = mysql-bin' >> /etc/mysql/conf.d/replication.cnf"
  - "echo 'server-id = 1' >> /etc/mysql/conf.d/replication.cnf"
  - "echo 'binlog-format = row'  >> /etc/mysql/conf.d/replication.cnf"
  - "sudo chmod 700 /etc/mysql/conf.d/replication.cnf"
  - "sudo service mysql restart"
script:
  - flake8 .
  - py.test
